---
title: "Fictitious data"
author: "John Kirkpatrick"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(knitr)
library(qtlr)
library("runjags")
runjags.options(silent.runjags = TRUE, silent.jags = TRUE)
```

```{r functions, include=FALSE}
interimMonth <- "09"
interimMonthName <- month.abb[as.integer(interimMonth)]
interimYear <- "2018"
qtls <- c(0.1, 0.9)

study1 <- tibble(Exposure=c(10, 10.5, 9.5, 11, 9, 8.5), 
                 Events=c(2, 2, 2, 2, 2, 2),
                 Rate=Events/Exposure)
study2 <- tibble(Exposure=c(10, 10.5, 9.5, 11, 9, 8.5), 
                 Events=c(1, 1, 1, 1, 1, 7),
                 Rate=Events/Exposure)
```

## Study 1

```{r, error=TRUE}

mBase <- fitPoissonModel(study1$Events, study1$Exposure)
fitIndex <-max(unique(mBase$Index), na.rm=TRUE)
mBasePlot <- mBase %>% filter(Parameter=="mu",
                              Index==fitIndex)

qtlColours <- c("darkgrey", "white", "darkgrey")
qtlLabels <-c("Low", "", "High")
qtlScale <- scale_fill_manual(name="QTL", labels=qtlLabels, values=qtlColours)

createQtlPlot(mBasePlot,
              groupData=study1,
              groupResponse=Rate,
              groupSize=Exposure,
              qtls=qtls,
              nDensity=2048,
              xAxisRange=c(0, 2)) + 
  labs(title="Study A") +
  qtlScale +
  scale_linetype_manual(labels=c("East", "ROW"), 
                        values=c("solid", "dashed"))

study1 %>% kable(digits=c(1, 0, 3))

limits <- qtlToQuantile(mBase %>% filter(Index==fitIndex), qtls)

limits %>% kable(digits=c(1, 3),
        table.attr="style='width:30%;'",
        col.names=c("Quantile", "Equivalent event rate"),
        caption="Derived action limits")
```

## Study 2

```{r, error=TRUE}

mBase <- fitPoissonModel(study2$Events, study2$Exposure)
fitIndex <-max(unique(mBase$Index), na.rm=TRUE)
mBasePlot <- mBase %>% filter(Parameter=="mu",
                              Index==fitIndex)

qtlColours <- c("darkgrey", "white", "darkgrey")
qtlLabels <-c("Low", "", "High")
qtlScale <- scale_fill_manual(name="QTL", labels=qtlLabels, values=qtlColours)

createQtlPlot(mBasePlot,
              groupData=study2,
              groupResponse=Rate,
              groupSize=Exposure,
              qtls=qtls,
              xAxisRange=c(0, 2)) + 
  labs(title="Study B") +
  qtlScale +
  scale_linetype_manual(labels=c("East", "ROW"), 
                        values=c("solid", "dashed"))

limits <- qtlToQuantile(mBase %>% filter(Index==fitIndex), qtls)

study2 %>% kable(digits=c(1, 0, 3))

limits %>% kable(digits=c(1, 3),
        table.attr="style='width:30%;'",
        col.names=c("Quantile", "Equivalent event rate"),
        caption="Derived action limits")
```
