---
title: "Figures 1 and 2"
author: "John Kirkpatrick"
date: "2/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(qtlr)
library(cowplot)
library(knitr)
library(kableExtra)
```

```{r init}
set.seed(071808)
qtls <- c(0.1, 0.9)
```

```{r generate}
centres <- tibble(Centre=1:15,
                  N=5+floor(20*runif(15)))

generateData <- function(rLabel, vLabel, a, b)
{
  d <- centres %>% 
         mutate(Prob=rbeta(15, a, b),
                Rate=rLabel,
                Var=vLabel,
                R=rbinom(15, N, Prob),
                ObservedRate=R/N)
  return (d)
}
data <- list()
data[[1]] <- generateData("Medium", "High",    2,    2)
data[[2]] <- generateData("Medium", "Medium", 10,   10)
data[[3]] <- generateData("Medium", "Low",    24.5, 24.5)
data[[4]] <- generateData("Low",    "High",    0.7,  2.1)
data[[5]] <- generateData("Low",    "Medium",  4,   12)
data[[6]] <- generateData("Low",    "Low",     9,   27)
data[[7]] <- generateData("High",   "High",    2.1,  0.7)
data[[8]] <- generateData("High",   "Medium", 12,    4)
data[[9]] <- generateData("High",   "Low",    27,    9)
data <- bind_rows(data) %>% 
          mutate(Rate=factor(Rate, levels=c("Low", "Medium", "High")),
                 Var=factor(Var, levels=c("Low", "Medium", "High"))) %>% 
          arrange(Rate, Var)
```

```{r analyse}
nestedData <- data %>%  
          group_by(Rate, Var) %>%
          nest(.key=Observed)
results <- nestedData %>% 
  mutate(QTL=map(Observed, function(x) fitBinomialModel(n=x$N, r=x$R) %>% filter(Index == 16)),
         Limits=map(QTL, function(x) qtlFromQuantile(x, qtls)))
                
tempFunc <- function(i)
{
  createQtlPlot(mcmcData=results$QTL[[i]] %>% filter(Index == 16), 
                groupData=results$Observed[[i]], 
                mcmcAlpha=0.5,
                groupResponse=ObservedRate, qtls=qtls) +
    coord_cartesian(xlim = c(0, 1)) +
    scale_fill_manual(values=c("grey", "white", "grey")) + 
    # labs(x=" ",
    #      title=sprintf("Rate: %s; Variation: %s", nestedData$Rate[i], nestedData$Var[i])) +
    labs(x=" ") +
    guides(fill=FALSE)
}

plots <- lapply(1:9, tempFunc)
```

```{r fig2}
tiff(filename="Figure2.tiff", width=4000, height=4000, res=800)
ggdraw() +
  draw_plot(plots[[7]], x=0.000, y=0.000, width=0.333, height=0.333) +
  draw_plot(plots[[8]], x=0.333, y=0.000, width=0.333, height=0.333) +
  draw_plot(plots[[9]], x=0.667, y=0.000, width=0.333, height=0.333) +
  draw_plot(plots[[4]], x=0.000, y=0.333, width=0.333, height=0.333) +
  draw_plot(plots[[5]], x=0.333, y=0.333, width=0.333, height=0.333) +
  draw_plot(plots[[6]], x=0.667, y=0.333, width=0.333, height=0.333) +
  draw_plot(plots[[1]], x=0.000, y=0.667, width=0.333, height=0.333) +
  draw_plot(plots[[2]], x=0.333, y=0.667, width=0.333, height=0.333) +
  draw_plot(plots[[3]], x=0.667, y=0.667, width=0.333, height=0.333)
dev.off()
```

```{r fig1}
tiff(filename="Figure1.tiff", width=4000, height=4000, res=800)
print(plots[[1]])
dev.off()
#ggsave("fig1.jpg", plot=plots[[1]])
```

```{r table2}
results %>% 
  unnest(Limits) %>% 
  spread(key=Quantile, value=QTL) %>% 
  rename("Lower"=`0.1`, "Upper"=`0.9`) %>% 
  kable(digits=2,
        table.attr = "style='width:50%;'",
        col.names=c("Mean", "Variation", "Lower (10th centile)", "Upper (90th centile)")) %>% 
  add_header_above(c(" "=2, "QTL limits"=2)) %>% 
  collapse_rows(columns = 1, valign = "top")

results %>%
  unnest(Limits) %>%
  spread(key=Quantile, value=QTL) %>%
  rename("Low"=3, "High"=4) %>%
  group_by(Rate, Var) %>%
  nest() %>%
  spread(key=Var, value=data) %>%
  unnest() %>%
  kable(digits=2,
        col.names=c("Rate", rep(sprintf("%.f%%", 100*qtls), times=3)),
        table.attr = "style='width:50%;'") %>%
  add_header_above(c(" "=1, "Low"=2, "Medium"=2, "High"=2)) %>%
  add_header_above(c(" "=1, "Variation"=6))
```
