---
title: "Figure 4"
author: "John Kirkpatrick"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(knitr)
library(qtlr)
#source("functions.R", echo=FALSE)

createQtlPlot <- function(mcmcData,
                          mcmcVar=Value,
                          groupData,
                          groupResponse=ObservedResponse,
                          groupSize=N,
                          groupType=NULL,
                          basicTheme=ggplot2::theme_light,
                          qtls=c(0.1, 0.2, 0.8, 0.9),
                          postScaleFactor=NULL,
                          mcmcAlpha=0.2,
                          nDensity=512)
{
  #Validate
  if (is.null(groupData)) stop("groupData cannot be null")
  if (is.null(quote(groupResponse))) stop("groupResponse cannot be null")
  if (!tibble::is_tibble(groupData)) stop("groupData must be a tibble")
  if (is.null(mcmcData)) stop("mcmcData cannot be null")
  if (!tibble::is_tibble(mcmcData)) stop("mcmcData must either be null or a tibble.")
  if (is.null(quote(mcmcVar))) stop("mcmcVar cannot be null")
  #Begin
  qResp <- dplyr::enquo(groupResponse)
  qSize <- dplyr::enquo(groupSize)
  if (!is.null(quote(groupType))) qGroup <- dplyr::enquo(groupType)
  qVar <- dplyr::enquo(mcmcVar)
  plot <- groupData %>% ggplot2::ggplot()
  #Plot the observed data
  if (is.null(qGroup)) {
    plot <- plot + ggplot2::geom_linerange(ggplot2::aes_q(x=qResp, ymin=0, ymax=qSize))
  } else {
    plot <- plot + ggplot2::geom_linerange(ggplot2::aes_q(x=qResp, ymin=0, ymax=qSize, linetype=qGroup))
  }
  #Plot the posterior density.  Could use geom_density directly, but shading
  #the action limits requires manipulation...
  if (!is.null(qtls) & length(qtls) > 0)
  {
    #Shading required
    if (is.null(postScaleFactor)) postScaleFactor <- 2 * (groupData %>%  dplyr::summarise(Max=max(!! qSize)))$Max[1]
    qtlTibble <- qtlFromQuantile(mcmcData, qtls)
    d <- ggplot2::ggplot_build(mcmcData %>%
                                 ggplot2::ggplot() +
                                 ggplot2::geom_density(ggplot2::aes_q(qVar, y=~..scaled..*postScaleFactor),
                                                       n=nDensity)
    )$data[[1]]
    d <- d %>% dplyr::mutate(Area=cut(x,
                                      breaks=c(-Inf, qtlTibble$QTL, Inf),
                                      labels=1:(nrow(qtlTibble)+1)))
    plot <- plot +
      ggplot2::geom_line(data=d, ggplot2::aes(x=x, y=y))
    for (a in unique(d$Area))
      plot <- plot + ggplot2::geom_area(data=d %>% dplyr::filter(Area == a),
                                        ggplot2::aes(x=x, y=y, fill=Area),
                                        alpha=mcmcAlpha,
                                        show.legend=FALSE)
  } else {
    #No shading required
    plot <- plot + ggplot2::geom_density(data=mcmcData,
                                         ggplot2::aes_q(qVar, y=~..scaled..*30),
                                         n=nDensity)
  }
  plot <- plot +
    basicTheme() +
    ggplot2::theme(axis.ticks.y=ggplot2::element_blank(),
                   axis.text.y=ggplot2::element_blank(),
                   axis.title.y=ggplot2::element_blank())
  return(plot)
}
```

```{r functions, include=FALSE}
maxPlotRate <- 20
interimMonth <- "09"
interimMonthName <- month.abb[as.integer(interimMonth)]
interimYear <- "2018"
qtls <- c(0.1, 0.9)
```

```{r}
# aeBase <- readData(paste0(interimYear, interimMonth)) %>%
#             filter(Exposure > 0.2)
# saveRDS(aeBase, "Figure4.RData")

aeBase <- readRDS("Figure4.RData") %>%
            filter(Exposure > 0.2)
```

```{r}
mBase <- fitPoissonModel(aeBase$EventCount, aeBase$Exposure)
fitIndex <- max(unique(mBase$Index), na.rm=TRUE)
mBasePlot <- mBase %>% filter(Parameter=="mu",
                              Index==fitIndex,
                              Value < maxPlotRate)

qtlColours <- c("darkgrey", "white", "darkgrey")
qtlLabels <-c("Low", "", "High")
qtlScale <- scale_fill_manual(name="QTL", labels=qtlLabels, values=qtlColours)

tiff(filename="Figure4.tiff", width=4500, height=3000, res=800)
createQtlPlot(mBasePlot,
              groupData=aeBase,
              groupResponse=Rate,
              groupSize=Subjects,
              groupType=Region,
              qtls=qtls,
              nDensity=2048) + 
  labs(title=" ") +
  qtlScale +
  scale_linetype_manual(values=c("dashed", "solid"))
dev.off()

createQtlPlot(mBasePlot,
              groupData=aeBase,
              groupResponse=Rate,
              groupSize=Subjects,
              groupType=Region,
              qtls=qtls,
              nDensity=2048) + 
  labs(title=" ") +
  qtlScale +
  scale_linetype_manual(values=c("dashed", "solid"))


limits <- qtlFromQuantile(mBase %>% filter(Index==fitIndex), qtls)

limits %>% kable(digits=c(1, 3),
        table.attr="style='width:30%;'",
        colnames=c("Quantile", "equivalent event rate"),
        caption="Derived action limits")

results <-  mBase %>%
              filter(Parameter == "mu") %>%
              group_by(Parameter, Index) %>%
              summarise(Fitted=mean(Value)) %>%
              ungroup()

aeBase <- aeBase %>% 
            mutate(Index=1:(fitIndex-1)) %>% 
            full_join(results, by="Index") %>% 
            select(-Parameter)

aeBase <- aeBase %>%
            mutate(Band=cut(Rate,
                            breaks=c(-Inf, limits$QTL, Inf),
                            labels=c("Low", "OK", "High"))) %>% 
            filter(!is.na(Region))

aeBase %>% 
  select(Centre, Country, Subjects, Exposure, EventCount, Rate, Fitted, Region, Band) %>% 
  filter(Band != "OK") %>% 
  arrange(Rate) %>% 
  kable(digits=c(0, NA, 0, 2, 0, 2, 2, NA, NA),
        table.attr="style='width:30%;'",
        caption="Centres in the 'Low' or 'High' investigation ranges")

aeBase %>% 
  group_by(Region) %>% 
  summarise(N=n()) %>% 
  kable(caption="Centres by region")

aeBase %>% 
  group_by(Region, Band) %>% 
  summarise(N=n()) %>% 
  ungroup() %>% 
  spread(key=Band, value=N)
```


