---
title: "WA29767"
author: "John Kirkpatrick"
date: "Last run on `r Sys.Date()` by `r Sys.info()[['user']]` on `r Sys.info()['nodename']`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(knitr)
library(qtlr)

#Overwrite createQtlPlot function from qtlr to allow linetype rather than colour
#to indicate group membership
createQtlPlot <- function(mcmcData,
                          mcmcVar=Value,
                          groupData,
                          groupResponse=ObservedResponse,
                          groupSize=N,
                          groupType=NULL,
                          basicTheme=ggplot2::theme_light,
                          qtls=c(0.1, 0.2, 0.8, 0.9),
                          postScaleFactor=NULL,
                          mcmcAlpha=0.2,
                          nDensity=512,
                          xAxisRange=NULL)
{
  #Validate
  if (is.null(groupData)) stop("groupData cannot be null")
  if (is.null(quote(groupResponse))) stop("groupResponse cannot be null")
  if (!tibble::is_tibble(groupData)) stop("groupData must be a tibble")
  if (is.null(mcmcData)) stop("mcmcData cannot be null")
  if (!tibble::is_tibble(mcmcData)) stop("mcmcData must either be null or a tibble.")
  if (is.null(quote(mcmcVar))) stop("mcmcVar cannot be null")
  if (!is.null(xAxisRange)) if (length(xAxisRange) != 2) stop("xAxisRange must either be NULL or a numeric vector of length 2")
  #Begin
  qResp <- dplyr::enquo(groupResponse)
  qSize <- dplyr::enquo(groupSize)
  if (!is.null(quote(groupType))) qGroup <- dplyr::enquo(groupType)
  qVar <- dplyr::enquo(mcmcVar)
  plot <- groupData %>% ggplot2::ggplot()
  #Plot the observed data
  if (is.null(qGroup)) {
    plot <- plot + ggplot2::geom_linerange(ggplot2::aes_q(x=qResp, ymin=0, ymax=qSize))
  } else {
    plot <- plot + ggplot2::geom_linerange(ggplot2::aes_q(x=qResp, ymin=0, ymax=qSize, linetype=qGroup))
  }
  #Plot the posterior density.  Could use geom_density directly, but shading
  #the action limits requires manipulation...
  if (is.null(postScaleFactor)) postScaleFactor <- 2 * (groupData %>%  dplyr::summarise(Max=max(!! qSize)))$Max[1]
  if (!is.null(qtls) & length(qtls) > 0)
  {
    #Shading required
    qtlTibble <- qtlToQuantile(mcmcData, qtls)
    d <- ggplot2::ggplot_build(mcmcData %>% 
                    ggplot2::ggplot() +
                    ggplot2::geom_density(ggplot2::aes_q(qVar, y=~..scaled..*postScaleFactor), 
                                          n=nDensity)
                      )$data[[1]]
    d <- d %>% dplyr::mutate(Area=cut(x, 
                               breaks=c(-Inf, qtlTibble$Quantile, Inf),
                               labels=1:(nrow(qtlTibble)+1)))
    plot <- plot +
              ggplot2::geom_line(data=d, ggplot2::aes(x=x, y=y))
    for (a in unique(d$Area))
      plot <- plot + ggplot2::geom_area(data=d %>% dplyr::filter(Area == a),
                               ggplot2::aes(x=x, y=y, fill=Area),
                               alpha=mcmcAlpha)
  } else {
    #No shading required
    plot <- plot + ggplot2::geom_density(data=mcmcData,
                                         ggplot2::aes_q(qVar, y=~..scaled..*postScaleFactor), 
                                         n=nDensity)
  }
  plot <- plot + 
           basicTheme() +
           ggplot2::theme(axis.ticks.y=ggplot2::element_blank(),
                          axis.text.y=ggplot2::element_blank(),
                          axis.title.y=ggplot2::element_blank())
  if (!is.null(xAxisRange)) plot <- plot + ggplot2::coord_cartesian(xlim=xAxisRange)
  return(plot)
}

# readData <- function(folder)
# {
#   ae <- read_bce(paste0("/opt/bee/home_NEW/kirkpatj/R/QTL_test_data/WA29767/", folder, "/ae.sas7bdat"))
#   dm  <- read_bce(paste0("/opt/bee/home_NEW/kirkpatj/R/QTL_test_data/WA29767/", folder, "/dm.sas7bdat"))
#   rv <- createSummaryData(ae, dm)
#   # rv <- rv %>%
#   #   add_column(Timepoint=paste0(substr(folder, 1, 4), "-", substr(folder, 5, 6)))
#   return (rv)
# }
# 
# mapCountryToRegion <- function(data)
# {
#   mapping <- list("ARG"="ROW",  "BEL"="ROW", "BUL"="East", "CAN"="ROW",
#                   "DEN"="ROW", "ESP"="ROW", "GBR"="ROW", "GER"="ROW",
#                   "GRE"="ROW", "HUN"="East", "ITA"="ROW", "JPN"="ROW",
#                   "LTU"="East", "MEX"="ROW", "NED"="ROW", "POL"="East",
#                   "POR"="ROW", "ROM"="East", "SUI"="ROW", "USA"="ROW")
#   mapping <- mapping[unique(data$Country)]
#   data <- data %>%
#     mutate(Region=factor(Country,
#                          labels=unlist(mapping, use.names=FALSE),
#                          levels=sort(unique(Country))))
#   return (data)
# }
# 
# createSummaryData <- function(aeData, dmData)
# {
#   ae <- aeData %>%
#     #Create columns for Study, Centre and Subject
#     separate(USUBJID, c("Study", "Centre", "Subject")) %>%
#     #Convert character start dates to Dates
#     mutate(AESTDT=ymd(AESTDTC, quiet=TRUE)) %>%
#     #Handle incomplete start dates
#     mutate(AESTDT=ifelse(is.na(AESTDT), ymd(paste0(AESTDTC, "-01"), quiet=TRUE), AESTDT)) %>%
#     mutate(AESTDT=ifelse(is.na(AESTDT), ymd(paste0(AESTDTC, "-01-01"), quiet=TRUE), AESTDT)) %>%
#     select(-STUDYID)
#   dm <- dmData %>%
#     separate(USUBJID, c("Study", "Centre", "Subject")) %>%
#     mutate(RFENDT=ymd_hm(RFENDTC),
#            RFSTDT=ymd_hm(RFSTDTC),
#            Exposure=interval(RFSTDT, RFENDT)/dyears(1)) %>%
#     replace_na(list(Exposure=0)) %>%
#     select(Study, Centre, Subject, Exposure, COUNTRY, RFENDT) %>%
#     rename(Country=COUNTRY)
# 
#   #Filter to AEs with an onset no more than 30 days after the last dose of study
#   #drug.
#   ae <- ae %>%
#     left_join(dm, by=c("Study", "Centre", "Subject")) %>%
#     filter(AESTDT <= (RFENDT + days(30))) %>%
#     select(-RFENDT)
# 
#   aeCounts <- ae %>%
#     group_by(Study, Centre, Subject) %>%
#     summarise(EventCount=n()) %>%
#     ungroup()
# 
#   aeSummary <- dm %>%
#     left_join(aeCounts, by=c("Study", "Centre", "Subject")) %>%
#     replace_na(list(EventCount=0)) %>%
#     group_by(Study, Centre, Country) %>%
#     summarise(Subjects=n(),
#               Exposure=sum(Exposure),
#               EventCount=sum(EventCount),
#               Rate=ifelse(Exposure > 0, EventCount/Exposure, 0)) %>%
#     ungroup() %>%
#     filter(Exposure > 0)
#   aeSummary <- mapCountryToRegion(aeSummary)
#   return (aeSummary)
# }
# 
# aeBase <- readData("201709")
# saveRDS(aeBase, "aeBase.RData")
```

```{r functions, include=FALSE}
maxPlotRate <- 30
interimMonth <- "09"
interimMonthName <- month.abb[as.integer(interimMonth)]
interimYear <- "2018"
qtls <- c(0.1, 0.9)
```

```{r, error=TRUE}
aeBase <- readRDS("aeBase.RData")

aeBase %>% filter(is.na(Region))

mBase <- fitPoissonModel(aeBase$EventCount, aeBase$Exposure)
fitIndex <-max(unique(mBase$Index), na.rm=TRUE)
mBasePlot <- mBase %>% filter(Parameter=="mu",
                              Index==fitIndex,
                              Value < maxPlotRate)

qtlColours <- c("darkgrey", "white", "darkgrey")
qtlLabels <-c("Low", "", "High")
qtlScale <- scale_fill_manual(name="QTL", labels=qtlLabels, values=qtlColours)

createQtlPlot(mBasePlot,
              groupData=aeBase,
              groupResponse=Rate,
              groupSize=Subjects,
              groupType=Region,
              qtls=qtls,
              nDensity=2048) + 
  labs(title=" ") +
  qtlScale +
  scale_linetype_manual(labels=c("ROW", "East"), 
                        values=c("dashed", "solid"))

limits <- qtlToQuantile(mBase %>% filter(Index==fitIndex), qtls)

limits %>% kable(digits=c(1, 3),
        table.attr="style='width:30%;'",
        colnames=c("Quantile", "equivalent event rate"),
        caption="Derived action limits")

results <-  mBase %>%
              filter(Parameter == "mu") %>%
              group_by(Parameter, Index) %>%
              summarise(Fitted=mean(Value)) %>%
              ungroup()

aeBase <- aeBase %>% 
            mutate(Index=1:(fitIndex-1)) %>% 
            full_join(results, by="Index") %>% 
            select(-Parameter)

aeBase <- aeBase %>%
            mutate(Band=cut(Rate,
                            breaks=c(-Inf, limits$Quantile, Inf),
                            labels=c("Low", "OK", "High"))) %>% 
            filter(!is.na(Region))

aeBase %>% 
  select(Centre, Country, Subjects, Exposure, EventCount, Rate, Fitted, Region, Band) %>% 
  filter(Band != "OK") %>% 
  arrange(Rate) %>% 
  kable(digits=c(NA, NA, 0, 2, 0, 2, 2, NA, NA),
        table.attr="style='width:30%;'",
        caption="Centres in the 'Low' or 'High' investigation ranges")

aeBase %>% 
  group_by(Region) %>% 
  summarise(N=n()) %>% 
  kable(caption="Centres by region")

aeBase %>% 
  group_by(Region, Band) %>% 
  summarise(N=n()) %>% 
  ungroup() %>% 
  spread(key=Band, value=N)
```


