---
title: "Figures 1 and 2"
author: "John Kirkpatrick"
date: "Last run on `r Sys.Date()` by `r Sys.info()[['user']]` on `r Sys.info()['nodename']`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(qtlr)
library(cowplot)
library(knitr)
library(kableExtra)
library(png)
```

```{r init}
set.seed(071808)
qtls <- c(0.1, 0.9)
```

```{r generate}
centres <- tibble(Centre=1:15,
                  N=5+floor(20*runif(15)))

generateData <- function(rLabel, vLabel, a, b)
{
  d <- centres %>% 
         mutate(Prob=rbeta(15, a, b),
                Rate=rLabel,
                Var=vLabel,
                R=rbinom(15, N, Prob),
                ObservedRate=R/N)
  return (d)
}
data <- list()
data[[1]] <- generateData("Medium", "High",    2,    2)
data[[2]] <- generateData("Medium", "Medium", 10,   10)
data[[3]] <- generateData("Medium", "Low",    24.5, 24.5)
data[[4]] <- generateData("Low",    "High",    0.7,  2.1)
data[[5]] <- generateData("Low",    "Medium",  4,   12)
data[[6]] <- generateData("Low",    "Low",     9,   27)
data[[7]] <- generateData("High",   "High",    2.1,  0.7)
data[[8]] <- generateData("High",   "Medium", 12,    4)
data[[9]] <- generateData("High",   "Low",    27,    9)
data <- bind_rows(data) %>% 
          mutate(Rate=factor(Rate, levels=c("Low", "Medium", "High")),
                 Var=factor(Var, levels=c("Low", "Medium", "High"))) %>% 
          arrange(Rate, Var)
```

```{r analyse}
nestedData <- data %>%  
                group_by(Rate, Var) %>%
                nest(Observed=c(Centre, N, Prob, R, ObservedRate))
results <- nestedData %>% 
             mutate(
               QTL=map(Observed, function(x) fitBinomialModel(n=x$N, r=x$R) %>% filter(Index == 16)),
               Limits=map(QTL, function(x) qtlFromQuantile(x, qtls))
             )
```

```{r fig1}
tempFunc <- function(i)
{
  print(i)
  createQtlPlot(mcmcData=results$QTL[[i]] %>% filter(Index == 16), 
                groupData=results$Observed[[i]], 
                mcmcAlpha=0.5,
                groupResponse=ObservedRate, qtls=qtls) +
    theme(
      axis.title.y=element_text(angle=90, size=8),
      axis.title.x=element_text(size=8),
    ) + #Override createQtlPlot default
    coord_cartesian(xlim = c(0, 1)) +
    scale_fill_manual(values=c("grey", "white", "grey")) + 
    labs(
      x="Rate", 
      y="Density"
    ) +
    guides(fill=FALSE)
}

plots <- lapply(1:9, tempFunc)

title <- ggdraw() +
           draw_label("Figure 1: Changes in the posterior with the location and variance of observed data", x=0.0, hjust=0,
                      size=10)
fNote <- ggdraw() +
           draw_label(
             size=6,
             hjust=0,
             x=0.0,
             "The x co-ordinates of vertical bars give the observed centre-specific event rates; their heights are proportional to centre sizes")

plots <- ggdraw() +
           draw_plot(plots[[7]], x=0.000, y=0.000, width=0.333, height=0.333) +
           draw_plot(plots[[8]], x=0.333, y=0.000, width=0.333, height=0.333) +
           draw_plot(plots[[9]], x=0.667, y=0.000, width=0.333, height=0.333) +
           draw_plot(plots[[4]], x=0.000, y=0.333, width=0.333, height=0.333) +
           draw_plot(plots[[5]], x=0.333, y=0.333, width=0.333, height=0.333) +
           draw_plot(plots[[6]], x=0.667, y=0.333, width=0.333, height=0.333) +
           draw_plot(plots[[1]], x=0.000, y=0.667, width=0.333, height=0.333) +
           draw_plot(plots[[2]], x=0.333, y=0.667, width=0.333, height=0.333) +
           draw_plot(plots[[3]], x=0.667, y=0.667, width=0.333, height=0.333)

combinedPlot <- plot_grid(
                  title, plots, fNote,
                  ncol = 1,
                  rel_heights = c(0.1, 1, 0.025)
                )
print(combinedPlot)

#Save to file
tiff(filename="Figure1.tiff", width=4000, height=4000, res=800)
print(combinedPlot)
dev.off()

png(filename="Figure1.png", width=1200, height=1200, res=240)
print(combinedPlot)
dev.off()
```

```{r table2}
results %>%   
  select(Rate, Var, Limits) %>% 
  unnest(Limits) %>% 
  spread(key=Quantile, value=QTL) %>% 
  rename("Lower"=`0.1`, "Upper"=`0.9`) %>% 
  kable(digits=2,
        table.attr = "style='width:50%;'",
        col.names=c("Mean", "Variation", "Lower (10th centile)", "Upper (90th centile)")) %>% 
  add_header_above(c(" "=2, "QTL limits"=2)) %>% 
  collapse_rows(columns = 1, valign = "top")

results %>%  
  select(Rate, Var, Limits) %>% 
  unnest(Limits) %>%
  spread(key=Quantile, value=QTL) %>%
  rename("Low"=3, "High"=4) %>%
  group_by(Rate, Var) %>%
  nest() %>%
  spread(key=Var, value=data) %>%
  unnest() %>%
  kable(digits=2,
        col.names=c("Rate", rep(sprintf("%.f%%", 100*qtls), times=3)),
        table.attr = "style='width:50%;'") %>%
  add_header_above(c(" "=1, "Low"=2, "Medium"=2, "High"=2)) %>%
  add_header_above(c(" "=1, "Variation"=6))
```
## Environment
```{r}
sessionInfo()
```